shanbay/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from . import views

shanbay/main/views.py
# coding=utf-8
from flask import render_template, flash, Markup, redirect, url_for, current_app, request
from . import bp
from flask_login import current_user, login_required
from ..models import User, Note, Word
from itsdangerous import JSONWebSignatureSerializer
from .. import db


@bp.route('/', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        name = current_user.username
        if request.method == 'GET':
            user = User.query.filter_by(username=name).first()
            is_new_user = user.new_user
            if is_new_user:
                flash(Markup('你是新新新新, 新来的吧, 来<a href="/settings">设置</a>每日计划吧'))

            return render_template('main/index.html', name=name)
        else:
            data = request.form
            words_per_day = data['words_per_day']
            return render_template('main/index.html', name=name, words_per_day=words_per_day)
    else:
        return render_template('main/index.html', name='there')


@bp.route('/review', methods=['GET', 'POST'])
@login_required
def review():
    if current_user.is_authenticated:
        username = current_user.username

        # generate token for authenticating user
        s = JSONWebSignatureSerializer('token', salt=current_app.config['SECRET_KEY'])
        token = s.dumps({'username': username})
        token = token.decode()

        user = User.query.filter_by(username=username).first()
        words_per_day = user.words_per_day
        words = user.words.limit(words_per_day).all()
        return render_template('main/review.html', words=words, token=token, words_per_day=words_per_day)
    else:
        return redirect(url_for('account.login'))


@bp.route('/submit_note', methods=['POST', 'GET'])
def submit_note():
    if request.method == 'POST':
        s = JSONWebSignatureSerializer('token', salt=current_app.config['SECRET_KEY'])
        data = request.form
        note_content = data['note']
        word_id = data['word_id']
        token = data['user_id']

        username = s.loads(token)['username']

        word = Word.query.get(word_id)
        user = User.query.filter_by(username=username).first()
        note = Note(content=note_content)

        user.notes.append(note)
        word.notes.append(note)

        for t in (word, user, note):
            db.session.add(t)
        db.session.commit()
    return redirect(url_for('main.review'))


@bp.route('/words_known')
@bp.route('/words_known/<int:page>')
def words_known(page=1):
    user = User.query.filter_by(username=current_user.username).first()
    words_known = user.words_known.paginate(page, 10, False)
    return render_template('main/words_known.html',
                            user=user,
                            words_known=words_known)


@bp.route('/words_unknown')
@bp.route('/words_unknown/<int:page>')
def words_unknown(page=1):
    user = User.query.filter_by(username=current_user.username).first()
    words_unknown = user.words.paginate(page, 10, False)

    return render_template('main/words_unknown.html', 
                           user=user,
                           words_unknown=words_unknown)

shanbay/templates/main/index.html
{% extends "layout.html" %}
{% block subtitle %}首页{% endblock %}

shanbay/templates/main/review.html
{% extends "layout.html" %}
{% block subtitle %}学习{% endblock %}

{% block content %}
  <div class="container">
  <div class="col-md-2"></div>
  <div class="col-md-8">
  <input id="token" value="{{ token }}" type="hidden">
  {% for word in words %}
    <ul id="{{ loop.index }}" data-id="{{ word.id }}" class="word hidden">
        <div class="word-text">
          <h1>{{ word.word }}</h1> <h3><span class="label label-info">{{ loop.index }}/{{ words_per_day }}</span></h3>
        </div>

        <div class="options">
          <button id="indexId-{{ loop.index }}" data-id="{{ word.id }}"
                  class="btn btn-success known" type="button"
                  onclick="handle_result('known', this.id, $(this).attr('data-id'))">认识</button>
          <button id="unknown-{{ loop.index }}" data-id="{{ word.id }}"
                  class="btn btn-danger unknown" type="button"
                  onclick="handle_result('unknown', this.id, $(this).attr('data-id'))">不认识</button>
        </div>

        <div class="detail hidden">
          <div class="page-header">
            <label>翻译</label>
          </div>
          <h4><span class="label label-primary">{{ word.category }}</span></h4>
          <h4>{{ word.translation }}</h4>
          <a id="buttonId-{{ loop.index }}" class="btn btn-default hidden next" type="button" href="#"
             onclick="next(this.id, {{ words_per_day }})">下一个</a>

          <!-- notes here -->
          <div class="page-header"><label>笔记</label></div>
          <div class="note" id="note-{{ loop.index }}">
          </div>

          <div class="form-group">
            <form method="POST" id="note-form" action="submit_note">
              <label for="comment">记笔记:</label>
              <textarea class="form-control" rows="5" id="note-textarea" name="note"></textarea>
              <input type="hidden" value="{{ word.id }}" name="word_id">
              <input type="hidden" value="{{ token }}" name="user_id">
              <input id="submit-note-btn" type="submit" class="btn btn-default" value="Submit"
                     onsubmit="validateNoteTextarea()">
            </form>
          </div>
        </div>
    </ul>
  {% endfor %}
  <div class="col-md-2"></div>
{% endblock %}

shanbay/templates/main/words_known.html
{% extends "layout.html" %}
{% block subtitle %}已掌握单词{% endblock %}

{% block content %}
	<div class="container">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			{% for word in words_known.items %}
				<div>
				{{ word.word }}
				{{ word.translation }}
				</div>
			{% endfor %}
			{% if not words_known.items %}
				<div>还没有掌握的单词, 还不快去学习? 点<a href="{{ url_for('main.review') }}">这里</a></div>
			{% endif %}
			{% if words_known.items %}
				{% if words_known.has_prev %}<a href="{{ url_for('main.words_known', page=words_known.prev_num) }}">&lt;&lt; 上一页</a>{% else %}&lt;&lt; 下一页{% endif %} | 
				{% if words_known.has_next %}<a href="{{ url_for('main.words_known', page=words_known.next_num) }}">上一页 &gt;&gt;</a>{% else %}下一页 &gt;&gt;{% endif %}
			{% endif %}
		</div>
		<div class="col-md-2"></div>
	</div>
{% endblock %}

shanbay/templates/main/words_unknown.html
{% extends "layout.html" %}
{% block subtitle %}未掌握单词{% endblock %}
{% block content %}
	<div class="container">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			{% for word in words_unknown.items %}
				<div>
					{{ word.word }}
					{{ word.translation }}
				</div>
			{% endfor %}
			{% if words_unknown.items %}
				{% if words_unknown.has_prev %}<a href="{{ url_for('main.words_unknown', page=words_unknown.prev_num) }}">&lt;&lt; 上一页</a>{% else %}&lt;&lt; 下一页{% endif %} | 
				{% if words_unknown.has_next %}<a href="{{ url_for('main.words_unknown', page=words_unknown.next_num) }}">上一页 &gt;&gt;</a>{% else %}下一页 &gt;&gt;{% endif %}
			{% endif %}
		</div>
		<div class="col-md-2"></div>
	</div>
{% endblock %}